"""EMU API asosida avtomatik yaratilgan hudud ma'lumotlari.

Bu faylni qo'lda tahrirlamang - `python tools/refresh_locations.py` bilan yangilanadi.
Manba: https://apiv1.emu.uz (regions, cities, branches) + templates/branch_codes.xlsx
"""

GENERATED_AT = "2026-08-17"

# (region_id, uz_name, ru_name, center_city_id)
REGIONS = (
    (1, "Andijon viloyati", "Андижанская область", 1),
    (2, "Buxoro viloyati", "Бухарская область", 3),
    (3, "Farg‘ona viloyati", "Ферганская область", 11),
    (4, "Jizzax viloyati", "Джизакская область", 4),
    (5, "Qashqadaryo viloyati", "Кашкадарьинская область", 5),
    (6, "Xorazm viloyati", "Хорезмская область", 10),
    (7, "Namangan viloyati", "Наманганская область", 7),
    (8, "Navoiy viloyati", "Навоийская область", 6),
    (9, "Qoraqalpog‘iston Respublikasi", "Республика Каракалпакстан", 8),
    (10, "Samarqand viloyati", "Самаркандская область", 2),
    (11, "Surxondaryo viloyati", "Сурхандарьинская область", 9),
    (12, "Sirdaryo viloyati", "Сырдарьинская область", 12),
    (13, "Toshkent", "Ташкент", 198),
    (14, "Toshkent viloyati", "Ташкентская область", 182),
)

# (city_id, region_id, uz_name, ru_name, server_name, offices)
CITIES = (
    (1, 1, "Andijon shahri", "город Андижан", "Андижан", ("Andijon Eski shahar", "Andijon Yangi shahar", )),
    (13, 1, "Xonobod shahri", "город Ханабад", "Ханабад", ("Qorasuv", "Xonobod", )),
    (34, 1, "Andijon tumani", "Андижанский район", "Куйган - яр", ("Kuyganyor", )),
    (47, 1, "Asaka tumani", "Асакинский район", "Асака", ("Asaka", )),
    (61, 1, "Baliqchi tumani", "Балыкчинский район", "Балыкчи", ("Baliqchi", "Chinobod", )),
    (75, 1, "Bo‘z tumani", "Бозский район", "Боз", ("Boʻston", )),
    (89, 1, "Buloqboshi tumani", "Булакбашинский район", "Булокбоши", ("Buloqboshi", )),
    (103, 1, "Jalaquduq tumani", "Жалакудукский район", "Джалакудук", ("Jalaquduq", )),
    (117, 1, "Izboskan tumani", "Избасканский район", "Избаскан", ("Izboskan", )),
    (131, 1, "Qo‘rg‘ontepa tumani", "Кургантепинский район", "Кургантепа", ("Qoʻrgʻontepa", )),
    (145, 1, "Marhamat tumani", "Мархаматский район", "Мархамат", ("Marhamat", )),
    (157, 1, "Paxtaobod tumani", "Пахтаабадский район", "Пахтаабад", ("Paxtaobod", )),
    (169, 1, "Ulug‘nor tumani", "Улугнорский район", "Улугнор", ("Oqoltin", )),
    (177, 1, "Oltinko‘l tumani", "Алтынкульский район", "Алтинкул", ("Oltinkoʻl", )),
    (184, 1, "Xo‘jaobod tumani", "Ходжаабадский район", "Ходжаабад", ("Xo'jaobod", )),
    (191, 1, "Shahrixon tumani", "Шахриханский район", "Шахрихан", ("Shahrixon", )),
    (3, 2, "Buxoro shahri", "город Бухара", "Бухара", ("Buxoro Mikrorayon", "Buxoro Vokzal", )),
    (17, 2, "Olot tumani", "Алатский район", "Алат", ("Olot", )),
    (37, 2, "Buxoro tumani", "Бухарский район", "Галлаасия", ("Galaosiyo", )),
    (50, 2, "Vobkent tumani", "Вабкентский район", "Вабкент", ("Vobkent", )),
    (64, 2, "G‘ijduvon tumani", "Гиждуванский район", "Гиждуван", ("Gijduvon", )),
    (78, 2, "Jondor tumani", "Жондорский район", "Джандар", ("Jondor", )),
    (92, 2, "Kogon tumani", "Каганский район", "Каган", ("Kogon", )),
    (106, 2, "Qorako‘l tumani", "Каракульский район", "Каракуль", ("Qorako'l", )),
    (120, 2, "Qorovulbozor tumani", "Караулбазарский район", "Караулбазар", ("Qorovulbozor", )),
    (134, 2, "Peshku tumani", "Пешкунский район", "Пешку", ("Peshku", )),
    (148, 2, "Romitan tumani", "Ромитанский район", "Ромитан", ("Romitan", )),
    (160, 2, "Shofirkon tumani", "Шафирканский район", "Шафиркан", ("Shofirkon", )),
    (11, 3, "Farg‘ona shahri", "город Фергана", "Фергана", ("Farg'ona Festival", "Farg'ona Qirguli", )),
    (29, 3, "Qo‘qon shahri", "город Коканд", "Коканд", ("Quqon bozor", "Quqon Charhiy", "Quqon Navoiy", )),
    (30, 3, "Quvasoy shahri", "город Кувасай", "Кувасай", ("Quvasoy", )),
    (31, 3, "Marg‘ilon shahri", "город Маргилан", "Маргилан", ("Margilan", )),
    (45, 3, "Bag‘dod tumani", "Багдадский район", "Багдад", ("Bagʻdod", )),
    (59, 3, "Beshariq tumani", "Бешарыкский район", "Бешарык", ("Beshariq", )),
    (73, 3, "Buvayda tumani", "Бувайдинский район", "Бувайда", ("Buvayda", )),
    (87, 3, "Dangara tumani", "Дангаринский район", "Дангара", ()),
    (101, 3, "Kuva tumani", "Кувинский район", "Кува", ("Quva", )),
    (115, 3, "Oltiariq tumani", "Алтыарыкский район", "Алтыарык", ("Oltiariq", )),
    (129, 3, "Qo‘shtepa tumani", "Куштепинский район", "Куштепа", ("Qoʻshtepa", )),
    (143, 3, "Rishton tumani", "Риштанский район", "Риштан", ("Rishton", )),
    (156, 3, "So‘x tumani", "Сохский район", "Сох", ()),
    (168, 3, "Toshloq tumani", "Ташлакский район", "Ташлак", ("Toshloq", )),
    (176, 3, "O‘zbekiston tumani", "Узбекистанский район", "Яйпан", ("Yaypan", )),
    (183, 3, "Uchko‘prik tumani", "Учкуприкский район", "Учкуприк", ("Uchko'prik", )),
    (190, 3, "Farg‘ona tumani", "Ферганский район", "Водил", ("Vodil", )),
    (193, 3, "Furqat tumani", "Фуркатский район", "Навбахор", ("Furqat", )),
    (196, 3, "Yozyovon tumani", "Язъяванский район", "Язъяван", ("Yozyovon", )),
    (4, 4, "Jizzax shahri", "город Джизак", "Джизак", ("Jizzax Zargarlik", )),
    (18, 4, "Arnasoy tumani", "Арнасайский район", "Арнасай", ("Arnasoy", )),
    (38, 4, "Baxmal tumani", "Бахмальский район", "Бахмал", ("Baxmal", )),
    (51, 4, "G‘allaorol tumani", "Галляаральский район", "Галляарал", ("G'allaorol", )),
    (65, 4, "Sharof Rashidov tumani", "Шараф-Рашидовский район", "Шараф-Рашидов", ("Sharof Rashidov", )),
    (79, 4, "Do‘stlik tumani", "Дустликский район", "Дустлик", ("Doʻstlik", )),
    (93, 4, "Zomin tumani", "Зааминский район", "Заамин", ("Zomin", )),
    (107, 4, "Zarbdor tumani", "Зарбдарский район", "Зарбдар", ("Zarbdor", )),
    (121, 4, "Zafarobod tumani", "Зафарабадский район", "Зафарабад", ("Zafarobod", )),
    (135, 4, "Mirzacho‘l tumani", "Мирзачульский район", "Гагарин", ("Gagarin", )),
    (149, 4, "Paxtakor tumani", "Пахтакорский район", "Пахтакор", ("Paxtakor", )),
    (161, 4, "Forish tumani", "Фаришский район", "Янгикишлак", ("Forish", )),
    (171, 4, "Yangiobod tumani", "Янгиабадский район", "Балангачкыр", ("Yangiobod", )),
    (5, 5, "Qarshi shahri", "город Карши", "Карши", ("Qarshi Komilon", "Qarshi Osiyo Bozor", )),
    (19, 5, "G‘uzor tumani", "Гузарский район", "Гузар", ("Guzor", )),
    (39, 5, "Dehqonobod tumani", "Дехканабадский район", "Дехканабадский район", ("Karashina", )),
    (52, 5, "Qamashi tumani", "Камашинский район", "Камаши", ("Qamashi", )),
    (66, 5, "Qarshi tumani", "Каршинский район", "Бешкент", ("Beshkent", )),
    (80, 5, "Koson tumani", "Касанский район", "Касан", ("Koson", )),
    (94, 5, "Kasbi tumani", "Касбийский район", "Касбий", ("Kasbi", )),
    (108, 5, "Kitob tumani", "Китабский район", "Китоб", ("Kitob", )),
    (122, 5, "Mirishkor tumani", "Миришкорский район", "Миришкор", ("Mirishkor", )),
    (136, 5, "Muborak tumani", "Мубарекский район", "Мубарек", ("Muborak", )),
    (150, 5, "Nishon tumani", "Нишанский район", "Нишан", ("Nishon", )),
    (162, 5, "Chiroqchi tumani", "Чиракчинский район", "Чиракчи", ("Chiroqchi", )),
    (172, 5, "Shahrisabz tumani", "Шахрисабзский район", "Шахрисабз", ("Shahrisabz Navro'z bog'i", "Shahrisabz Chinor Tagi", )),
    (179, 5, "Ko‘kdala tumani", "Кукдалинский район", "Кокдала", ("Koʻkdala", )),
    (186, 5, "Yakkabog‘ tumani", "Яккабагский район", "Яккабаг", ("Yakkabogʻ", )),
    (10, 6, "Urganch shahri", "город Ургенч", "Ургенч", ("Urganch Gastronom", "Urganch Mashʼal", )),
    (28, 6, "Bog‘ot tumani", "Багатский район", "Багат", ("Bogʻot", )),
    (44, 6, "Gurlan tumani", "Гурленский район", "Гурлен", ("Gurlan", )),
    (58, 6, "Qo‘shko‘pir tumani", "Кошкупырский район", "Кошкупыр", ("Qo'shko'pir", )),
    (72, 6, "Urganch tumani", "Ургенчский район", "Караул", ()),
    (86, 6, "Xazorasp tumani", "Хазараспский район", "Хазарасп", ("Hazarasp", )),
    (100, 6, "Xonqa tumani", "Ханкинский район", "Ханка", ("Xonqa", )),
    (114, 6, "Xiva tumani", "Хивинский район", "Хива", ("Xiva", )),
    (128, 6, "Shovot tumani", "Шаватский район", "Шават", ("Shovot", )),
    (142, 6, "Yangiariq tumani", "Янгиарыкский район", "Янгиарык", ("Yangiariq", )),
    (155, 6, "Yangibozor tumani", "Янгибазарский район", "Янгибазар", ("Yangibozor", )),
    (167, 6, "Tuproqqal’a tumani", "Тупроккалинский район", "Тупраккала", ("Pitnak", )),
    (7, 7, "Namangan shahri", "город Наманган", "Наманган", ("Namangan Mikrorayon", "Namangan Sardoba", )),
    (21, 7, "Kosonsoy tumani", "Касансайский район", "Касансай", ("Kosonsoy", )),
    (41, 7, "Mingbuloq tumani", "Мингбулакский район", "Джумашуй", ("Jumashuy", )),
    (54, 7, "Namangan tumani", "Наманганский район", "Ташбулак", ("Toshbuloq", )),
    (68, 7, "Norin tumani", "Нарынский район", "Хаккулабад", ("Xaqqulobod", )),
    (82, 7, "Pop tumani", "Папский район", "Пап", ("Pop", )),
    (96, 7, "To‘raqo‘rg‘on tumani", "Туракурганский район", "Туракурган", ("To'raqo'rg'on", )),
    (110, 7, "Uychi tumani", "Уйчинский район", "Уйчи", ("Uychi", )),
    (124, 7, "Uchqo‘rg‘on tumani", "Учкурганский район", "Учкурган", ("Uchqo'rg'on", )),
    (138, 7, "Chortoq tumani", "Чартакский район", "Чартак", ("Chortoq", )),
    (151, 7, "Chust tumani", "Чустский район", "Чуст", ("Chust", )),
    (163, 7, "Yangiqo‘rg‘on tumani", "Янгикурганский район", "Янгикурган", ("Yangiqoʻrgʻon", )),
    (6, 8, "Navoiy shahri", "город Навои", "Навои", ("Navoiy Voskhod", )),
    (20, 8, "Zarafshon shahri", "город Зарафшан", "Зарафшан", ("Zarafshon", )),
    (40, 8, "Konimex tumani", "Канимехский район", "Канимех", ("Konimex", )),
    (53, 8, "Karmana tumani", "Карманинский район", "Кармана", ()),
    (67, 8, "Qiziltepa tumani", "Кызылтепинский район", "Кызылтепа", ("Qiziltepa", )),
    (81, 8, "Navbahor tumani", "Навбахорский район", "Бешрабат", ("Beshrabot", )),
    (95, 8, "Nurota tumani", "Нуратинский район", "Нурата", ("Nurota", )),
    (109, 8, "Tomdi tumani", "Тамдынский район", "Тамдыбулак", ()),
    (123, 8, "Uchquduq tumani", "Учкудукский район", "Учкудук", ("Uchquduq", )),
    (137, 8, "Xatirchi tumani", "Хатырчинский район", "Хатырчи", ("Xatirchi", )),
    (8, 9, "Nukus shahri", "город Нукус", "Нукус", ("Nukus Tamojniy", )),
    (22, 9, "Amudaryo tumani", "Амударьинский район", "Амударья", ("Mangʻit", )),
    (42, 9, "Beruniy tumani", "Берунийский район", "Беруни", ("Beruniy", )),
    (55, 9, "Bo‘zatov tumani", "Бозатауский район", "Казакеткен", ()),
    (69, 9, "Qanliko‘l tumani", "Канлыкульский район", "Канлыкуль", ("Qanlikoʻl", )),
    (83, 9, "Qorao‘zak tumani", "Караузякский район", "Караузяк", ("Qoraoʻzak", )),
    (97, 9, "Kegeyli tumani", "Кегейлийский район", "Кегейли", ("Kegeyli", )),
    (111, 9, "Qo‘ng‘irot tumani", "Кунградский район", "Кунград", ("Qoʻngʻirot", )),
    (125, 9, "Mo‘ynoq tumani", "Муйнакский район", "Муйнак", ()),
    (139, 9, "Nukus tumani", "Нукусский район", "Акмангит", ("Aqmangit", )),
    (152, 9, "Taxtako‘pir tumani", "Тахтакупырский район", "Тахтакупыр", ("Taxtako'pir", )),
    (164, 9, "To‘rtko‘l tumani", "Турткульский район", "Турткуль", ("Toʻrtkoʻl", )),
    (173, 9, "Xo‘jayli tumani", "Ходжейлийский район", "Ходжейли", ("Xo'jayli", )),
    (180, 9, "Chimboy tumani", "Чимбайский район", "Чимбай", ("Chimboy", )),
    (187, 9, "Shumanay tumani", "Шуманайский район", "Шуманай", ("Shumanay", )),
    (192, 9, "Ellikqala tumani", "Элликкалинский район", "Элликкала", ("Ellikqalʼa", )),
    (194, 9, "Taqiyatosh tumani", "Тахиаташский район", "Тахиаташ", ("Taxiatosh", )),
    (2, 10, "Samarqand shahri", "город Самарканд", "Самарканд", ("Samarqand Panjakent", "Samarqand Qorasuv", "Samarqand Tadbirkorlar", "Samarqand Uzbekistanski", "Samarqand Vokzal", )),
    (16, 10, "Bulung‘ur tumani", "Булунгурский район", "Булунгур", ("Bulung'ur", )),
    (36, 10, "Jomboy tumani", "Джамбайский район", "Джамбай", ("Jomboy", )),
    (49, 10, "Ishtixon tumani", "Иштыханский район", "Иштыхан", ()),
    (63, 10, "Kattaqo‘rg‘on tumani", "Каттакурганский район", "Каттакурган", ("Kattaqorgon", "Payshanba", "Kattaqorgon Eski shahar", )),
    (77, 10, "Qo‘shrabot tumani", "Кошрабадский район", "Кушрабад", ()),
    (91, 10, "Narpay tumani", "Нарпайский район", "Акташ", ("Oqtosh", )),
    (105, 10, "Nurobod tumani", "Нурабадский район", "Нурабад", ("Nurobod", )),
    (119, 10, "Payariq tumani", "Пайарыкский район", "Пайарык", ("Chelak", )),
    (133, 10, "Pastdarg‘om tumani", "Пастдаргомский район", "Джума", ("Juma", )),
    (147, 10, "Paxtachi tumani", "Пахтачийский район", "Зиадин", ("Ziyovuddin", )),
    (159, 10, "Oqdaryo tumani", "Акдарьинский район", "Лаиш", ("Loyish", )),
    (170, 10, "Samarqand tumani", "Самаркандский район", "Гульабад", ("Seliski", )),
    (178, 10, "Tayloq tumani", "Тайлакский район", "Тайлак", ("Toyloq", )),
    (185, 10, "Urgut tumani", "Ургутский район", "Ургут", ("Urgut", )),
    (9, 11, "Termiz shahri", "город Термез", "Термез", ("Termiz Kurant", )),
    (23, 11, "Oltinsoy tumani", "Алтынсайский район", "Карлук", ("Oltinsoy", )),
    (43, 11, "Angor tumani", "Ангорский район", "Ангор", ("Angor", )),
    (56, 11, "Boysun tumani", "Байсунский район", "Байсун", ("Boysun", )),
    (70, 11, "Denov tumani", "Денауский район", "Денау", ("Denov O'zbegim", )),
    (84, 11, "Jarqo‘rg‘on tumani", "Джаркурганский район", "Джаркурган", ("Jarqo'rg'on", )),
    (98, 11, "Qiziriq tumani", "Кизирикский район", "Кизирик", ("Qiziriq", )),
    (112, 11, "Qumqo‘rg‘on tumani", "Кумкурганский район", "Кумкурган", ("Qumqoʻrgʻon", )),
    (126, 11, "Muzrabot tumani", "Музрабадский район", "Халкабад", ("Muzrabot", )),
    (140, 11, "Sariosiyo tumani", "Сариасийский район", "Сариасия", ("Sariosiyo", )),
    (153, 11, "Termiz tumani", "Термезский район", "Учкизил", ()),
    (165, 11, "Uzun tumani", "Узунский район", "Узун", ("Uzun", )),
    (174, 11, "Sherobod tumani", "Шерабадский район", "Шерабад", ("Sherobod", )),
    (181, 11, "Bandixon tumani", "Бандихонский район", "Бандихан", ("Bandixon", )),
    (188, 11, "Sho‘rchi tumani", "Шурчинский район", "Шурчи", ("Shoʻrchi", )),
    (12, 12, "Guliston shahri", "город Гулистан", "Гулистан", ("Guliston Oxunboboyev", "Guliston vokzal", )),
    (32, 12, "Shirin shahri", "город Ширин", "Ширин", ("Shirin", )),
    (33, 12, "Yangiyer shahri", "город Янгиер", "Янгиер", ("Yangiyer", )),
    (46, 12, "Boyovut tumani", "Баяутский район", "Баяут", ("Boyovut", )),
    (60, 12, "Guliston tumani", "Гулистанский район", "Дехканабад", ("Dehqonobod", )),
    (74, 12, "Mirzaobod tumani", "Мирзаабадский район", "Навруз", ()),
    (88, 12, "Sayxunobod tumani", "Сайхунабадский район", "Сайхун", ("Sayxunobod", )),
    (102, 12, "Sardoba tumani", "Сардобинский район", "Сардоба", ("Sardoba", )),
    (116, 12, "Sirdaryo tumani", "Сырдарьинский район", "Сырдарья", ("Baxt", "Sirdaryo", )),
    (130, 12, "Xovos tumani", "Хавастский район", "Хаваст", ()),
    (144, 12, "Oqoltin tumani", "Акалтынский район", "Акалтын", ()),
    (14, 13, "Bektemir tumani", "Бектемирский район", "Бектемир", ()),
    (15, 13, "Chilonzor tumani", "Чиланзарский район", "Чиланзар", ("Bek baraka", "Ippodrom", "Qatortol", )),
    (35, 13, "Mirabad tumani", "Мирабадский район", "Мирабад", ("Zelyoniy bozor", )),
    (48, 13, "Mirzo Ulug‘bek tumani", "Мирзо-Улугбекский район", "Мирзо-Улугбек", ("Feruza", "Mirzo Ulugbek", )),
    (62, 13, "Olmazor tumani", "Алмазарский район", "Алмазар", ("Qoraqamish", "Sebzor", "Tinchlik", )),
    (76, 13, "Sergeli tumani", "Сергелийский район", "Сергели", ("Massiv-5 Qo'yliq", "Sergeli", )),
    (90, 13, "Shayxontohur tumani", "Шайхантахурский район", "Шайхантахур", ("Chorsu", "Ibn Sino", "Malika", )),
    (104, 13, "Uchtepa tumani", "Учтепинский район", "Учтепа", ("O'rikzor", "Vatan", )),
    (118, 13, "Yakkasaroy tumani", "Яккасарайский район", "Яккасарай", ("Shota Rustaveli", )),
    (132, 13, "Yangihayot tumani", "Янгихаётский район", "Янгихаёт", ()),
    (146, 13, "Yashnobod tumani", "Яшнабадский район", "Яшнабад", ("Kadysheva", )),
    (158, 13, "Yunusobod tumani", "Юнусабадский район", "Юнусабад", ("Shahriston", )),
    (198, 13, "Toshkent", "Ташкент", "Ташкент", ("Toshkent Courier", )),
    (24, 14, "Olmaliq shahri", "город Алмалык", "Алмалык", ("Olmaliq", )),
    (25, 14, "Akkurgan tumani", "Аккурганский район", "Аккурган", ("Oqqo'rg'on", )),
    (26, 14, "Angren shahri", "город Ангрен", "Ангрен", ("Angren", )),
    (27, 14, "Chirchiq shahri", "город Чирчик", "Чирчик", ("Chirchiq", )),
    (57, 14, "Ohangaron tumani", "Ахангаранский район", "Ахангаран", ("Ohangaron", )),
    (71, 14, "Bekobod tumani", "Бекабадский район", "Бекабад", ("Bekabad", )),
    (85, 14, "Bo‘stonliq tumani", "Бостанлыкский район", "Газалкент", ("Gʻazalkent", )),
    (99, 14, "Bo‘ka tumani", "Букинский район", "Бука", ("Boʻka", )),
    (113, 14, "Zangiota tumani", "Зангиатинский район", "Зангиата", ("Eshonguzar", )),
    (127, 14, "Qibray tumani", "Кибрайский район", "Кибрай", ("Qibray", )),
    (141, 14, "Quyichirchiq tumani", "Куйичирчикский район", "Дустабад", ("Doʻstobod", )),
    (154, 14, "Parkent tumani", "Паркентский район", "Паркент", ("Parkent", )),
    (166, 14, "Pskent tumani", "Пскентский район", "Пскент", ("Piskent", )),
    (175, 14, "Toshkent tumani", "Ташкентский район", "Келес", ("Keles", )),
    (182, 14, "O‘rtachirchiq tumani", "Уртачирчикский район", "Нурафшон", ("Nurafshon", )),
    (189, 14, "Chinoz tumani", "Чиназский район", "Чиназ", ("Chinoz", )),
    (195, 14, "Yuqorichirchiq tumani", "Юкоричирчикский район", "Верхне-Чирчикский", ("Yuqorichirchiq", )),
    (197, 14, "Yangiyo‘l tumani", "Янгиюльский район", "Янгийоль", ("Yangiyo'l", )),
)
